parameters:
  - name: resources
    type: object
    displayName: Resources
  - name: condition
    displayName: Condition
    type: string
    default: succeeded()
  - name: stageName
    displayName: stageName
    type: string
    default: SetAggregateRunNumber
  - name: dependsOn
    displayName: Depends on
    type: object
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    displayName: Set aggregate run number
    ${{ if gt(length(parameters.dependsOn), 0) }}:      
      dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs: 
      - template: ../jobs/set-aggregate-run-number-job.yml
        parameters:
          resources: ${{ parameters.resources }}