parameters:
  - name: url
    displayName: URL
    type: string
  - name: solution
    displayName: Solution
    type: string
  - name: outputDirectory
    displayName: Output directory
    type: string
  - name: serviceConnection
    displayName: Service connection
    type: string
  - name: commitMessage
    displayName: Commit message
    type: string
  - name: branch
    displayName: Branch
    type: string
  - name: postUnpackSteps
    displayName: Post-unpack steps
    type: stepList
    default: []
  - name: mapFile
    displayName: Map File
    type: string
    default: ''
  - name: condition
    displayName: Condition
    type: string
    default: succeeded()
  - name: stageName
    displayName: Stage name
    type: string
    default: SyncSolutionMetadata
  - name: dependsOn
    displayName: Depends on
    type: object
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ format('Sync {0}', parameters.solution) }}
    ${{ if gt(length(parameters.dependsOn), 0) }}:      
      dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    jobs:
      - template: ../jobs/sync-solution-metadata-job.yml
        parameters:
          url: ${{ parameters.url }}
          solution: ${{ parameters.solution }}
          outputDirectory: ${{ parameters.outputDirectory }}
          serviceConnection: ${{ parameters.serviceConnection }}
          commitMessage: ${{ parameters.commitMessage }}
          branch: ${{ parameters.branch }}
          postUnpackSteps: ${{ parameters.postUnpackSteps }}
          mapFile : ${{ parameters.mapFile }}