name: $(GITVERSION_FullSemVer)

pool:
  vmImage: windows-latest

pr: none

trigger:
  batch: false
  branches:
    include:
      - master

resources:
  repositories:
    - repository: templates
      type: git
      name: power-platform-templates
      ref: refs/heads/master 

extends:
  template: platforms/power-platform/dataverse/pipelines/build-package-pipeline.yml@templates
  parameters:
    packageProject: deploy/Contoso.Sales.Deployment/Contoso.Sales.Deployment.csproj 
    serviceConnection: Sales Management App