parameters:
  - name: serviceConnection
    displayName: Service connection
    type: string
  - name: packageProject
    displayName: Package project
    type: string
  - name: unitTestsProject
    displayName: Unit tests project
    type: string
    default: ''
  - name: additionalProjects
    displayName: Additionals projects
    type: object
    default: []
  - name: filesToAnalyse
    displayName: Files to analyse (Solution Checker)
    type: string
    default: '**/*.zip'
  - name: dotNetSdkVersion
    displayName: .NET SDK version
    type: string
    default: 6.x

stages:
  - template: ../stages/build-package-stage.yml
    parameters:
      packageProject: ${{ parameters.packageProject }}
      unitTestsProject: ${{ parameters.unitTestsProject }}
      additionalProjects: ${{ parameters.additionalProjects }}
      dotNetSdkVersion: ${{ parameters.dotNetSdkVersion }}  
  - template: ../stages/solution-checker-stage.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      filesToAnalyse: ${{ parameters.filesToAnalyse }}
      artifact: package
